export default {
  LOGIN: 'LOGIN',
  SELECT_POSITION: 'SELECT_POSITION',
  LOGOUT: 'LOGOUT',
  NOTIFICATION: 'NOTIFICATION',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SELECT_FIELD: 'SELECT_FIELD',
  SELECT_REGION: 'SELECT_REGION',
  SET_ACTIVE_TOOLTIP: 'SET_ACTIVE_TOOLTIP',
};
