import request from './request';

export default {
  path: {
    login: '/auth/login',
    logout: '/auth/logout',
    detail_user: '/medical-record/detail',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    checkPhone: '/auth/check-phone',
    uploadAvatar: '/medical-record/avatar',
    activeProfile: '/medical-record/active-profile',
    updateProfile: '/medical-record/update-profile',
    updateField: '/fields/update-field-selected',
    getListField: '/fields/get-list-fields',
    getListFieldSelected: '/fields/get-list-field-selected',
    createFieldSelected: '/fields/create-field-selected',
    getProvince: '/address/province',
    getDistrict: '/address/district',
    getVillage: '/address/commune',
    getListJob: '/jobs/get-list-job',
    detailJob: '/jobs/detail-job',
    getAllJob: '/jobs/get-all-job',
    receivedProfile: '/jobs/received-profile',
    getJobCreated: '/jobs/list-create-job',
    list_interview: '/jobs/list-interview/partner',
    request_interview: '/jobs/request-interview',
    detailRequestInterview: '/jobs/detail-request-interview',
    acceptRequestInterview: '/jobs/accept-request-interview',
    createJob: '/jobs/create-job',
    submitProfile: '/jobs/submit-profile',
    submittedProfile: '/jobs/submitted-profile',
    listRequestInterview: '/jobs/list-request-interview',
    listCurriculumVitae: '/jobs/list-curriculum-vitae',
    manageRequestInterview: '/jobs/manage-request-interview',
    listNotifications: '/notification/list-notification',
    getReadNotifications: '/notification/get-read-notification',
    readNotifications: '/notification/read-notification',
    receivedJobPartner: '/jobs/manage-request-interview/partner',
    detailPartner: '/medical-record/detail-partner',
    statusJob: '/jobs/active-job/',
  },
  ...request,
};
